services:
  ollama:
      image: ollama/ollama:latest
      restart: unless-stopped
      ports:
        - 11434:11434
      volumes:
        - ./ollama/ollama:/root/.ollama
        - ./entrypoint.sh:/entrypoint.sh
      entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ./chroma:/chroma/.chroma/index
    ports:
      - 8000:8000